[build]
  command = "next build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["formidable"]
  included_files = ["public/uploads/**"]

[functions.upload]
  memory = 1024
  timeout = 30

[build.environment]
  NODE_VERSION = "18"
