[build]
  command = "next build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["formidable"]

[functions."api/upload"]
  included_files = []
  excluded_files = ["public/**/*"]

[build.environment]
  NODE_VERSION = "18"
  AWS_LAMBDA_FUNCTION_MEMORY_SIZE = "1024"
  AWS_LAMBDA_FUNCTION_TIMEOUT = "30"
